timezone: Asia/Calcutta
permalink: :title

# Custom URL Git Repo URL
baseurl: ''
url: //nishantmendiratta.github.io

# Default Git Repo URL
# baseurl: //nishantmendiratta.github.io/
# url: //nishantmendiratta.github.io

# Localhost Repo URL
# baseurl: ''
# url: http://localhost:4000